version: '3.7'
services:

  zipkin-server:
    image: "openzipkin/zipkin"
    ports:
      - 9411:9411
    volumes:
      - "./var-zipkin:/var/"

  eureka-server:
    image: "bloomberg/eureka-server:latest"
    ports:
      - "8761:8761"
    volumes:
      - "./var-eureka:/opt/app/logs"
    links:
      - zipkin-server:zipkin-server

  service-core:
    image: "bloomberg/calculator-service:latest"
    ports:
      - "50071"

    volumes:
      - "./var-core:/opt/app/logs"

    depends_on:
      - zipkin-server
      - eureka-server

    links:
      - zipkin-server:zipkin-server
      - eureka-server:eureka-server

    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
      - ZIPKIN_URI=http://zipkin-server:9411/

  service-client:
    image: "bloomberg/client-service:latest"
    ports:
      - "9000:9000"
    volumes:
      - "./var-client:/opt/app/logs"

    depends_on:
      - zipkin-server
      - eureka-server
      - service-core
    links:
      - zipkin-server:zipkin-server
      - eureka-server:eureka-server
      - service-core:service-core
    environment:
      - EUREKA_URI=http://eureka-server:8761/eureka
      - ZIPKIN_URI=http://zipkin-server:9411/

networks:
  default:
    external:
      name: bloomberg-network